"""empty message

Revision ID: 717484bcf97c
Revises: 8da1ae1ba09d
Create Date: 2020-12-09 10:35:19.041993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717484bcf97c'
down_revision = '8da1ae1ba09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racers', sa.Column('race_id', sa.Integer(), nullable=False))
    op.drop_constraint('racers_venue_id_fkey', 'racers', type_='foreignkey')
    op.create_foreign_key(None, 'racers', 'races', ['race_id'], ['id'])
    op.drop_column('racers', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racers', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'racers', type_='foreignkey')
    op.create_foreign_key('racers_venue_id_fkey', 'racers', 'venues', ['venue_id'], ['id'])
    op.drop_column('racers', 'race_id')
    # ### end Alembic commands ###
